---
title: "Feature analysis"
author: "Ruhi Mahadeshwar"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
data <- read.csv("~/Uni/Master thesis/linguistic_model/outputs/C-NNLA_output.csv")
head(data)
data <- na.omit(data)
lens <- read.csv("~/Uni/Master thesis/linguistic_model/lens.csv")
```

```{r}
par(mfrow=c(1,2), cex=0.5)

# sentence length
x = log(lens$length.of.sentence, base = exp(1))
max(lens$length.of.sentence)
h <- hist(x, breaks=10)
xfit<-seq(min(x),max(x),length=40)
mean(x)
sd(x)
yfit<-dnorm(xfit,mean=mean(x),sd=sd(x))
yfit <- yfit*diff(h$mids[1:2])*length(x)

lines(xfit, yfit, col="blue", lwd=2)

plot(density(x))
curve(dexp(x, rate = 0.4), col = 2, lty = 2, lwd = 2, add = TRUE)
```

```{r}
par(mfrow=c(1,2), cex=0.5)

# n/v
x = data$noun.verb
h <- hist(x, breaks=20)
xfit<-seq(min(x),max(x),length=40)
mean(x)
sd(x)
yfit<-dnorm(xfit,mean=mean(x),sd=sd(x))
yfit <- yfit*diff(h$mids[1:2])*length(x)

lines(xfit, yfit, col="blue", lwd=2)

plot(density(x))
```

```{r}
par(mfrow=c(2,2), cex=0.5)

# %n/all words
x = data$X..Nouns.all.words
h <- hist(x, breaks=20)
xfit<-seq(min(x),max(x),length=40)
yfit<-dnorm(xfit,mean=mean(x),sd=sd(x))
mean(x)
sd(x)
yfit <- yfit*diff(h$mids[1:2])*length(x)

lines(xfit, yfit, col="blue", lwd=2)

plot(density(x))

# nouns
y = data$Nouns
h <- hist(y, breaks=20)
xfit<-seq(min(y),max(y),length=40)
yfit<-dnorm(xfit,mean=mean(y),sd=sd(y))
yfit <- yfit*diff(h$mids[1:2])*length(y)

lines(xfit, yfit, col="blue", lwd=2)

plot(density(y))
```

```{r}
par(mfrow=c(2,2), cex=0.5)

# %v/all words
x = data$X..Verbs.all.words
h <- hist(x, breaks=20)
xfit<-seq(min(x),max(x),length=40)
yfit<-dnorm(xfit,mean=mean(x),sd=sd(x))
yfit <- yfit*diff(h$mids[1:2])*length(x)
mean(x)
sd(x)
min(x)
max(x)
lines(xfit, yfit, col="blue", lwd=2)

plot(density(x))

# verbs
y = data$Verbs
h <- hist(y, breaks=20)
xfit<-seq(min(y),max(y),length=40)
yfit<-dnorm(xfit,mean=mean(y),sd=sd(y))
yfit <- yfit*diff(h$mids[1:2])*length(y)

lines(xfit, yfit, col="blue", lwd=2)

plot(density(y))
```

```{r}
par(mfrow=c(1,2), cex=0.5)

# % prep
x = (data$prep./data$Total.Words)*100
h <- hist(x, breaks=20)
xfit<-seq(min(x),max(x),length=40)
yfit<-dnorm(xfit,mean=mean(x),sd=sd(x))
yfit <- yfit*diff(h$mids[1:2])*length(x)
lines(xfit, yfit, col="blue", lwd=2)
mean(x)
sd(x)
min(x)
max(x)
plot(density(x))
curve(dexp(x, rate = 0.025), col = 2, lty = 2, lwd = 2, add = TRUE)
```

```{r}
par(mfrow=c(1,2), cex=0.5)

# % det
x = (data$det./data$Total.Words)*100 # [data$prep. < 100]
h <- hist(x, breaks=20)
xfit<-seq(min(x),max(x),length=40)
yfit<-dnorm(xfit,mean=mean(x),sd=sd(x))
yfit <- yfit*diff(h$mids[1:2])*length(x)
lines(xfit, yfit, col="blue", lwd=2)
mean(x)
sd(x)
min(x)
max(x)
plot(density(x))
curve(dexp(x, rate = 0.025), col = 2, lty = 2, lwd = 2, add = TRUE)
```

```{r}
par(mfrow=c(1,2), cex=0.5)

# MLU in words (not reliable)
x = data$MLU.Words
h <- hist(x, breaks=20)
xfit<-seq(min(x),max(x),length=40)
yfit<-dnorm(xfit,mean=mean(x),sd=sd(x))
yfit <- yfit*diff(h$mids[1:2])*length(x)
mean(x)
sd(x)
min(x)
max(x)
lines(xfit, yfit, col="blue", lwd=2)

plot(density(x))

```

```{r}
par(mfrow=c(1,2), cex=0.5)

# % adj
x = (data$adj./data$Total.Words)*100 # [data$prep. < 100]
h <- hist(x, breaks=20)
xfit<-seq(min(x),max(x),length=40)
yfit<-dnorm(xfit,mean=mean(x),sd=sd(x))
yfit <- yfit*diff(h$mids[1:2])*length(x)
lines(xfit, yfit, col="blue", lwd=2)
mean(x)
sd(x)
min(x)
max(x)
plot(density(x))
curve(dexp(x, rate = 0.025), col = 2, lty = 2, lwd = 2, add = TRUE)
```

```{r}
par(mfrow=c(1,2), cex=0.5)

# % adv
x = (data$adv./data$Total.Words)*100 # [data$prep. < 100]
h <- hist(x, breaks=20)
xfit<-seq(min(x),max(x),length=40)
yfit<-dnorm(xfit,mean=mean(x),sd=sd(x))
yfit <- yfit*diff(h$mids[1:2])*length(x)
lines(xfit, yfit, col="blue", lwd=2)
mean(x)
sd(x)
min(x)
max(x)
plot(density(x))
curve(dexp(x, rate = 0.025), col = 2, lty = 2, lwd = 2, add = TRUE)
```